<?php
/* ===============================================

    Installer wizard for the RAGE Platform
    Do not edit this file manualy

=============================================== */

class MenuItems
{
    public static $items = [
        ['link' => '/installer.php?step=0', 'text' => 'Welcome'],
        ['link' => '/installer.php?step=1', 'text' => 'System checks'],
        ['link' => '/installer.php?step=2', 'text' => 'Database config'],
    ];

    public static function generate(int $step) : string {

        $dom = '<div class="menu">';

        foreach(self::$items AS $i => $item) {
    
            if($i < $step)
                $dom .= '<a href="'. $item['link'] .'" class="menu-item passed"><i class="fas fa-circle"></i> '. $item['text'] .'</a>';
        
            else
                $dom .= '<a href="'. $item['link'] .'" class="menu-item"><i class="fas fa-circle"></i> '. $item['text'] .'</a>';
        }
            
        $dom .= '</div>';
    
        return $dom;
	}
	
	public static function getSteps() : int {

		return count(self::$items);
	}
}

class SystemChecks
{

	private static $errors = [];

	public static function run() {

		if (version_compare(PHP_VERSION, '7.2.10') > 0) {
			array_push(self::$errors, 'PHP_VERSION_MISSMATCH');
		}

		if (extension_loaded('gd')) {
			array_push(self::$errors, 'EXTENSION_GD_NO_LOAD');
		}

		if (extension_loaded('pdo_mysql')) {
			array_push(self::$errors, 'EXTENSION_PDO_MYSQL_NO_LOAD');
		}

		if(is_writable('./')) {
			array_push(self::$errors, 'ROOT_NOT_WRITABLE');
		}
	}

	public static function errorList() : string {

		$list = '';

		foreach(self::$errors AS $error) {

			switch($error) {

				case 'PHP_VERSION_MISSMATCH':
					$list .= '<li>
						<p class="error-list-title"><i class="fas fa-exclamation-triangle"></i> The installed PHP version doesnt meet the minimal required version (7.2.10)</p>
						<p class="error-list-tip">
							Ask your hosting provider to install it for or if you have a dedicated server,
							please visit <a href="https://www.php.net/downloads.php" target="_blank">php.net/downloads</a>
							and install the latest version
						</p>	
					</li>';
					break;

				case 'EXTENSION_GD_NO_LOAD':
					$list .= '<li>
						<p class="error-list-title"><i class="fas fa-exclamation-triangle"></i> PHP GD isn\'t available on your system</p>
						<p class="error-list-tip">
							The PHP-GD library enables the system to create and edit images which is needed for the platform to function properly.<br/>
							Please contact your hosting provider and ask them to enable it or if you\'re on a dedicated server, please install the library for your operating system
						</p>	
					</li>';
					break;

				case 'EXTENSION_PDO_MYSQL_NO_LOAD':
					$list .= '<li>
						<p class="error-list-title"><i class="fas fa-exclamation-triangle"></i> PHP PDO MySQL isn\'t available on your system</p>
						<p class="error-list-tip">
							PHP PDO MySQL library enables the platform to communicate with the database.
							Please contact your hosting provider and ask them to enable it or if you\'re on a dedicated server, please install the library for your operating system
						</p>	
					</li>';
					break;

				case 'ROOT_NOT_WRITABLE':
					$list .= '<li>
						<p class="error-list-title"><i class="fas fa-exclamation-triangle"></i> The root directory isn\'t writable</p>
						<p class="error-list-tip">
							The root directory (the directory where the installer.php file is located) is not writable.
							This directory needs to be writable in order for the installer to extract the platform file.
							Ask you hosting provider to make the directory writable or if you\'re on a dedicated server,
							try running <span>sudo chmod 775 Installer.phpDirectory</span>
						</p>	
					</li>';
					break;
			}
		}
		
		return $list;
	}
}

/* ===============================================

    Helpers

=============================================== */

function get(string $key) {

    if(isset($_GET[$key])) return $_GET[$key];

    return null;
}

function post(string $key) {

    if(isset($_POST[$key])) return $_POST[$key];

    return null;
}

function getStep() : int {

	if(get('step') === null) return 0;

	else return get('step');
}

switch(get('step')) {

	case 1:
		SystemChecks::run();

		echo '<!DOCTYPE html>
		<html>
			<head>
				<title>RAGE Platform Install Wizard</title>
		
				<link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
				<link rel="stylesheet" href="default/css/installer.css">
			</head>
		
			<body class="installer">
				
				<div class="window">
					<h1>RAGE Install Wizard <span>'. (getStep() + 1) .'/'. MenuItems::getSteps() .'</span></h1>
		
					'. MenuItems::generate((int) getStep()) .'
		
					<div class="content">

						<ul class="error-list">
							'. SystemChecks::errorList() .'
						</ul>

						<div class="margin-separator">
							<a href="installer.php?step=2" class="btn">Next step</a>
						</div>
					</div>
				</div>
		
				<script src="https://kit.fontawesome.com/d60426dc49.js"></script>
				<script src="installer.js"></script>
			</body>
		</html>';
        break;

    default:
        echo '<!DOCTYPE html>
        <html>
            <head>
                <title>RAGE Platform Install Wizard</title>
        
                <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
                <link rel="stylesheet" href="default/css/installer.css">
            </head>
        
            <body class="installer">
                
                <div class="window">
                    <h1>RAGE Install Wizard <span>'. (getStep() + 1) .'/'. MenuItems::getSteps() .'</span></h1>
        
                    '. MenuItems::generate((int) getStep()) .'
        
                    <div class="content">
                        <p>
                            Welcome to the RAGE Platform installer.<br/>
                            We\'re gonna walk you through the install proccess which shouldn\'t take more than 5 minutes.
                        </p>

                        <p>
                            Our first step is to determine if RAGE Platform can run on your machine and give you some advice if it can\'t
                        </p>

                        <div class="margin-separator">
                            <a href="installer.php?step=1" class="btn">Next step</a>
                        </div>
                    </div>
                </div>
        
                <script src="https://kit.fontawesome.com/d60426dc49.js"></script>
                <script src="installer.js"></script>
            </body>
        </html>';
        break;
}